### PR TITLE
implement tryGet for all funs

### PR DESCRIPTION
**Pull request by kadyb**
- [x] Fix code.
- [x] Update tests.

### CODE REVIEW

**Comment by kadyb** [comment]
@Nowosad 
Please review and test. I did 10 tests with an internet connection and 10 without (i.e. disconnections) and everything worked. Definitely, this is not a perfect solution, but it works, so we can try get into CRAN.

**Comment by Nowosad** [comment]
My quick tests worked fine!

**Comment by kadyb** [comment]
Nice. Should I merge it now or wait for more tests from you? No hurry. Let be sure that it will meet the CRAN expectations.

**Comment by Nowosad** [comment]
I would suggest trying to submit to CRAN now. If there is still something wrong with the package - the CRAN team will let us know.

**Comment by kadyb** [comment]
More advanced connection checking function (`test_URL()`) can be found here: https://github.com/kadyb/rgugik/pull/21
but isn't working satisfactorily, requires further work.

**Pull request merged**
