### PR TITLE
Vig revs

### PR DESCRIPTION
**Pull request by Nowosad**

### CODE REVIEW

**Comment by kadyb** [comment]
1. "(...) plants and birds is protected" <- shouldn't there be "are"?
2. "centroid (geometric center)" <- it may be better to leave the explanation in brackets, because not everyone can be familiar with a centroid term.
3. "allows working" or "allows to work"? In `orthophotomap.Rmd` is "which allows to work with spatiotemporal arrays".
4. "The matrix cells contain exactly the same areas." <- areas (in terms of extent) of rasters are the same from the beginning. I think the word "object" is more accurate, or the word "information".
5. **Raster attributes**. I would leave an explanation of the attributes with examples, this concept needs to be explained to beginners.
6. "which we can convert into a simple geometry" <- we "must" rather than we "can", otherwise the function won't work.
7. "# first layer only" <- change it to "plot DEM" and name chunk - maybe "LINE".
8. "col = hcl.colors(9, palette = "RdYlGn")" maybe let's leave the single color scale, because the range starts from 0.

**Comment by Nowosad** [comment]
>     1. "(...) plants and birds is protected" <- shouldn't there be "are"?
> 
>     2. "centroid (geometric center)" <- it may be better to leave the explanation in brackets, because not everyone can be familiar with a centroid term.
> 
>     3. "allows working" or "allows to work"? In `orthophotomap.Rmd` is "which allows to work with spatiotemporal arrays".
> 
>     4. "The matrix cells contain exactly the same areas." <- areas (in terms of extent) of rasters are the same from the beginning. I think the word "object" is more accurate, or the word "information".
> 
>     5. **Raster attributes**. I would leave an explanation of the attributes with examples, this concept needs to be explained to beginners.
> 
>     6. "which we can convert into a simple geometry" <- we "must" rather than we "can", otherwise the function won't work.
> 
>     7. "# first layer only" <- change it to "plot DTM" and name chunk - maybe "LINE".
> 
>     8. "col = hcl.colors(9, palette = "RdYlGn")" <- maybe let's leave the single color scale, because the range starts from 0.

1. Depends on the context. 

A/ In addition, the oak-hornbeam forest with rare species of plants (*lilium martagon*, *ceratophyllum submersum*) and birds (*european nightjar*, *black woodpecker*) is protected. (Here - forest is protected)
B/ ~~In addition, the oak-hornbeam forest with rare species of plants (*lilium martagon*, *ceratophyllum submersum*) and birds (*european nightjar*, *black woodpecker*) are protected.~~ (Incorrect)
C/ In addition, it is covered by the oak-hornbeam forest with rare species of plants (*lilium martagon*, *ceratophyllum submersum*) and birds (*european nightjar*, *black woodpecker*) protected. (Here - plants and birds are protected)

3. Both are fine, although "allows working" is usually better.
4. I would suggest avoiding the term "object" - cells are not objects, and a cell does not represent any object. Cell is just a discretization of a space. 
5. Explanation of what are attributes, etc. could be useful here. However, the previous version was hard to understand and read.
Feel free to change 2, 6-8.

**Comment by kadyb** [comment]
Comparison of `extract` functions by line in:

**raster**
```r
pts_matrix = matrix(c(357121.7, 515765.5,
                      357321.2, 516017.9),
                    ncol = 2, byrow = TRUE)
line = spLines(pts_matrix, crs = CRS('+init=EPSG:2180'))
elev_line = extract(DTM, line)[[1]]
```

**stars**
```r
pts_matrix = matrix(c(357121.7, 515765.5,
                      357321.2, 516017.9),
                    ncol = 2, byrow = TRUE)
line = st_sfc(st_linestring(pts_matrix), crs = 2180)
line = st_line_sample(line, density = 1)
line = st_cast(line, "POINT")
elev_line = st_extract(DEM, line)[[1]]
```

So, it is much easier and user-friendly in **raster**.

**Comment by Nowosad** [comment]
> Comparison of `extract` functions by line in:
> 
> **raster**
> 
> ```r
> pts_matrix = matrix(c(357121.7, 515765.5,
>                       357321.2, 516017.9),
>                     ncol = 2, byrow = TRUE)
> line = spLines(pts_matrix, crs = CRS('+init=EPSG:2180'))
> elev_line = extract(DTM, line)[[1]]
> ```
> 
> **stars**
> 
> ```r
> pts_matrix = matrix(c(357121.7, 515765.5,
>                       357321.2, 516017.9),
>                     ncol = 2, byrow = TRUE)
> line = st_sfc(st_linestring(pts_matrix), crs = 2180)
> line = st_line_sample(line, density = 1)
> line = st_cast(line, "POINT")
> elev_line = st_extract(DEM, line)[[1]]
> ```
> 
> So, it is much easier and user-friendly in **raster**.

Yep, for many operations **raster** is more user-friendly. (Sidenote: you should avoid using `CRS('+init=EPSG:2180')`).
You can also prepare a reprex and suggest adding support for lines to `st_extract()`.

**Comment by kadyb** [comment]
https://github.com/r-spatial/stars/issues/334

**Comment by kadyb** [comment]
4. Maybe "The matrix contains exactly the same areas at the cell level."? Or leave it as it is?

**Comment by Nowosad** [comment]
How about replacing "We now can combine our models into one stack.
The matrix cells contain exactly the same areas." to 

"Now, both models have the same dimensions (the number of rows and columns) and spatial resolution. 
Thus, we can combine them into one object."
?

**Comment by kadyb** [comment]
I like it, I will use it.

**Pull request merged**
