### PR TITLE
better way to generate geometries

### PR DESCRIPTION
**Pull request by kadyb**

### CODE REVIEW

**Comment by kadyb** [comment]
@Nowosad, do you know how to create a sf object from WKB lists? Currently, this code doesn't work. Related are lines 88, 103, 104 and 108.

**Comment by Nowosad** [comment]
See my updated code. I think it fixes the issue and improves some other code elements.

Is this what you expect?

**Comment by Nowosad** [comment]
Your list in the above example consists of `sfg` objects. However, in the code, we have `sfc` objects:
https://github.com/kadyb/rgugik/blob/53935259c7c83ceb03d2cf3ba17d74d931c58917/R/borders_get.R#L105

**Comment by kadyb** [comment]
I asked yet [here](https://github.com/r-spatial/sf/issues/1950) and there is no other method than using concatenation.

**Pull request merged**
