### PR TITLE
Outdir

### PR DESCRIPTION
**Pull request by Nowosad**
Adds outdir and unzip arguments (where valid)

### CODE REVIEW

**Comment by kadyb** [comment]
Before your update, we had such a conditional statement in `tile_download`:
```r
if (!check_SHA) {
  # loop
} else {
   # loop
}
```
After update it is:
```r
loop {
   if (!check_SHA)
}
```
There is another condition in the next update `if (unzip && ext == "zip")`. Don't we significantly lose performance by checking 3 conditions in every loop iteration?

**Comment by Nowosad** [comment]
> Before your update, we had such a conditional statement in `tile_download`:
> 
> ```r
> if (!check_SHA) {
>   # loop
> } else {
>    # loop
> }
> ```
> 
> After update it is:
> 
> ```r
> loop {
>    if (!check_SHA)
> }
> ```
> 
> There is another condition in the next update `if (unzip && ext == "zip")`. Don't we significantly lose performance by checking 3 conditions in every loop iteration?

Good question. My intuition is that there will not be any significant lost of performance  due to this `if` statement. Downloading of one file can take seconds or more. Execution of one `if` statement, on the other hand, is measured in nanoseconds (10<sup>-9</sup> of a second; see e.g., https://stackoverflow.com/a/34005546/2602477).

**Comment by kadyb** [comment]
Test `models3D_download` after update and it works:
```r
models3D_download(TERYT = c("2462", "0401"), LOD = "LOD1",
                  outdir = "C:/Users/Krzysztof/Desktop/test1", unzip = FALSE)

models3D_download(TERYT = c("2462", "0401"), LOD = "LOD1",
                  outdir = "C:/Users/Krzysztof/Desktop/test2", unzip = TRUE)

models3D_download(TERYT = c("2462", "0401"), LOD = "LOD1",
                  outdir = "test1", unzip = FALSE)

models3D_download(TERYT = c("2462", "0401"), LOD = "LOD1",
                  outdir = "test2", unzip = TRUE)
```

**Comment by kadyb** [comment]
Test `tile_download` after update and it works:
```r
### orto
req_df = orto_request(polygon)
tile_download(req_df[1, ], check_SHA = TRUE)
req_df[1, "sha1"]
as.character(openssl::sha1(file("41_3756_N-33-130-D-b-2-3.tif")))

### DEM 1 (zip)
req_df = DEM_request(polygon)
req_df$sha1[1] = "XXX" # fake SHA
tile_download(req_df[1, ], outdir = "test", check_SHA = TRUE)
# should return warning

### DEM 2 (asc)
tile_download(req_df[3, ], outdir = "test", check_SHA = TRUE)
req_df[3, "sha1"]
as.character(openssl::sha1(file("test/2730_318577_N-33-130-D-b-2-3.asc")))

### DEM 3 (zip)
tile_download(req_df[7, ], outdir = "test", check_SHA = TRUE, unzip = FALSE)
req_df[7, "sha1"]
as.character(openssl::sha1(file("test/5132_384975_N-33-130-D-b-2_asc.zip")))
```

**Comment by kadyb** [comment]
@Nowosad please review code after my updates and try it on Linux. If all is OK, please merge it. Before merge regenerate docs, I didn't do it because generating polish characters doesn't work for me.

The issue of examples of using relative and absolute paths in the documentation has not been resolved. I think the examples will be too long (not minimal).

**Pull request merged**
