### PR TITLE
remove spaces in URL (fixes #83)

### LINKED ISSUE #83: How to debug connection error?
Hi @kadyb -- I tried to use `ortho_request()` today, but without any success. Now, the question is -- is it my local problem, **rgugik** issue, or GUGiK's servers problem?

``` r
library(rgugik)
library(sf)
#> Linking to GEOS 3.9.2, GDAL 3.3.2, PROJ 8.2.0
polygon_path = system.file("datasets/search_area.gpkg", package = "rgugik")
polygon = read_sf(polygon_path)
req_df = ortho_request(polygon)
req_df
#> [1] "connection error"
```

This issues is partially related to https://github.com/kadyb/rgugik/issues/81.

CC: @krystiano200

### PR DESCRIPTION
**Pull request by kadyb**

### CODE REVIEW

**Comment by Nowosad** [comment]
It works on my example (I also fixed broken/outdated urls).

**Comment by kadyb** [comment]
Most of these links don't work now (redirect to https://www.gov.pl/). Only `http://www.gugik.gov.pl` should be change to `https://www.gov.pl/web/gugik`, the rest should stay the same.

Check:
```
Before: http://www.gugik.gov.pl/pzgik/zamow-dane/numeryczny-model-terenu
After: https://www.gov.pl/web/gugik/pzgik/zamow-dane/numeryczny-model-terenu
```

**Comment by kadyb** [comment]
`vignettes/DEM.Rmd` <- if I remember correctly, the change should be made in `DEM.Rmd.orig` becouse we generate Rmd files using `vignettes/PRECOMPILE.R` script

**Comment by Nowosad** [comment]
Thanks for checking the links. I think some of them should be fixed before CRAN submission, but this is a different issue. I reverted most of the changes now.

**Pull request merged**
