### PR TITLE
added information about the date

### PR DESCRIPTION
**Pull request by BERENZ**
In this pull request I include information about the date of aerial or satellite photos based in `akt_data` variable available in GUGIK API. This information is crucial if you work with time series data and you would like to know for exactly what period these ortophotomaps are vaild.

### CODE REVIEW

**Comment by kadyb** [comment]
Thanks for contributing!
1. Could you change the order of the columns to match the GUGiK database? `akt_data` should be after `sha1`. `#akt_data = numeric()` in 58 line should be uncommented. I think it will make easier to detect some errors if something will change on the server side.
2. Could you update test in **test-orto_request.R**? Now we expect 12 columns as the output.

Note that the older orthophotomaps don't have an exact date (it will always be 01 January).

**Comment by BERENZ** [comment]
Done. Hope this is what you expected.

**Comment by kadyb** [comment]
Yeah. Please change order in `selected_cols` too (26-28 lines).

**Comment by kadyb** [comment]
Thanks!

**Pull request merged**
